- src.ts/pipeline/world.ts
Calls to World.removeCollider currently fail because the wrong method on physics pipeline is invoked. This PR fixes the call.
> world.removeCollider fix

- .gitignore
- package.json
- src.ts/geometry/shape.ts
- webpack.config.js
I had some trouble getting bundlers to work with the `.wasm` file: parcel did not work at all, and webpack requires an experiment "syncWebAssembly", but then type definitions did not work. The newer "asyncWebAssembly" also does not work.
Until bundlers are ready I think it would be easier to include the WebAssembly file as base64 and load it explicitly.
This PR replaces the build scripts with a package.json and webpack based build which
* Inlines the wasm as base64
* Minifies
* Outputs an UMD library which can be used with bundlers and in browsers directly by using a script tag
* Works on more plattforms (on macOS `sed` requires different parameters)
This way the library is easier to use and you could offer examples on Codepen because no bundler is required.
The downsides are:
* before …
> Webpack based build system, inline wasm as base64

- CHANGELOG.md
- src.ts/dynamics/rigid_body.ts
- src.ts/geometry/shape.ts
- src/geometry/collider.rs
- testbed3d/src/demos/lockedRotations.js
- Fix crash happening when creating a collider with a `ColliderDesc.convexHull` shape.
- Actually remove the second argument of `RigidBodyDesc.setMass` as mentioned in the 0.3.0 changelog.
- Improve snapshotting performances.
> Various minor fixes and snapshotting performance improvements

- rapier-compat/package.json
- rapier-compat/tsconfig.common.json
- rapier-compat/tsconfig.pkg2d.json
- rapier-compat/tsconfig.pkg3d.json
- rapier-compat/webpack.config.js
- rapier2d/build_typescript.sh
- rapier2d/tsconfig.json
- rapier3d/build_typescript.sh
- rapier3d/tsconfig.json
and rapier2d packages. (rapier-compat package structure not changed.)
Changes the typescript_build.sh script to copy the .ts
files into 'pkg/src' instead of 'pkg'. Adjusts the tsconfig.json
file so that it looks for sources in both 'pkg' and 'pkg/src'.
Also isolate the rapier-compat build from the rapier3d and rapier2d
build directories. rapier-compat still includes build artifacts
from these other directories, but no longer overwrites any of the
files there.
Verified that generated source maps point to the correct location.
In general, mixing .ts sources and generated .js and .d.ts in the
same directory can cause problems for downstream consumers of
the library. Some bundlers will preferentially load the .ts files
instead of the .js files, which will generate syntax errors if
the …
> Separate generated JavaScript from TypeScript source in rapier3d

- CHANGELOG.md
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
- src.ts/dynamics/joint.ts
- src.ts/dynamics/joint_set.ts
- src.ts/dynamics/rigid_body.ts
- src.ts/dynamics/rigid_body_set.ts
- src.ts/geometry/collider.ts
- src.ts/geometry/collider_set.ts
- src.ts/geometry/ray.ts
- src.ts/pipeline/physics_hooks.ts
- src.ts/pipeline/physics_pipeline.ts
- src.ts/pipeline/query_pipeline.ts
- src.ts/pipeline/world.ts
- src/dynamics/joint.rs
- src/dynamics/joint_set.rs
- src/dynamics/rigid_body.rs
- src/dynamics/rigid_body_set.rs
- src/geometry/collider.rs
- src/geometry/collider_set.rs
- src/geometry/mod.rs
- src/pipeline/physics_pipeline.rs
- src/pipeline/query_pipeline.rs
- testbed2d/package.json
- testbed3d/package.json
- testbed3d/src/PhysicsDescription.js
- The `World.castRay` and `World.castRayAndGetNormal` methods have a different signature now, making them
more flexible.
- Rename `ActiveHooks::FILTER_CONTACT_PAIR` to `ActiveHooks.FILTER_CONTACT_PAIRS`.
- Rename `ActiveHooks::FILTER_INTERSECTION_PAIR` to `ActiveHooks.FILTER_INTERSECTION_PAIRS`.
- Rename `BodyStatus` to `RigidBodyType`.  
- Rename `RigidBody.bodyStatus()` to `RigidBody.bodyType()`.
- Rename `RigidBodyDesc.setMassProperties` to `RigidBodyDesc.setAdditionalMassProperties`.
- Rename `RigidBodyDesc.setPrincipalAngularInertia` to `RigidBodyDesc.setAdditionalPrincipalAngularInertia`.
- Rename `ColliderDesc.setIsSensor` to `ColliderDesc.setSensor.
- Add `Ray.pointAt(t)` that conveniently computes `ray.origin + ray.dir * t`.
- Add access to joint motors by defining each joint …
> Add missing bindings

- rapier-compat/README.md
- rapier-compat/package.json
- rapier-compat/tests/World2d.test.ts
- rapier-compat/tests/World3d.test.ts
- rapier-compat/tests/math2d.test.ts
- rapier-compat/tests/math3d.test.ts
- rapier-compat/tsconfig.json
This PR demonstrates a unit test for rapier-compat (2d and 3d) which initalizes WASM, creates a World object, and tests one of its methods.
> Basic framework for TypeScript unit tests.

- testbed3d/src/demos/joints.js
RAPIER.BodyStatus is currently undefined. This PR replaces RAPIER.BodyStatus by RAPIER.RigidBodyType.
The variable 'status' was also renamed accordingly.
> Update 'joints' example

- CHANGELOG.md
- src/geometry/collider.rs
> Return a valid half-extent for round cuboids.

- rapier-compat/package.json
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
- src/geometry/collider_set.rs
This PR fixes the case where the collider creation would fail if it isn’t attached to any parent _and_ no rigid-bodies have been added since the beginning of the physics setup.
> Fix collider creation when it has no parent

- rapier-compat/package.json
- src.ts/geometry/collider.ts
- src/geometry/collider.rs
- src/geometry/narrow_phase.rs
- src/geometry/toi.rs
This PR fixes some typos in the lookup ID's, exposes the collider restitution, and also pins the rollup typescript version as 8.2.4 was causing a bug with compilation.
> Expose Restitution and fix lookup IDs

- src/geometry/collider.rs
- src/pipeline/query_pipeline.rs
This fixes `collider.setShape` and `world.collidersWithAabbIntersectingAabb` that crashed because of a null pointer error.
Fix #50
> Fix some null pointer crashes

- src.ts/geometry/collider.ts
- src.ts/geometry/point.ts
- src.ts/geometry/ray.ts
- src/dynamics/joint.rs
- src/geometry/collider.rs
- src/geometry/point.rs
- src/geometry/ray.rs
This adds methods to the `Collider` object: `containsPoint, projectPoint, castRay, castRayAndGetNormal, intersectsRay`.
This also fixes the ordering of joint variants (fix #68).
> Add bindings to cast rays or project points on a single collider

- src.ts/geometry/collider.ts
- src/geometry/collider.rs
`collider.parent()` will now return `undefined` that indicates it does not have parent.
fix for #89
> optional `collider.parent()`

- src/geometry/collider.rs
1, for retrieve 
```
segment.a / .b
triangle.a / .b / .c
```
because there is no such API on `Collider`
so implemented on `vertices`
if wanna retrieve `segment.a / .b` or `triangle.a / .b / .c`, use `c.vertices` instead
2, `c.roundRadius()` now available for all round shapes
tested and now `c.borderRadius()` and `c.vertices()` work correctly.
> fix for #60

- src.ts/pipeline/world.ts
Calling `world.removeRigidBody()` etc after `world.free()` results in a runtime error. You can workaround this issue in user-land but for convenience it would be nice if Rapier handled this automatically
> skip world.remove*() after world.free()

- rapier-compat/tsconfig.common.json
- rapier-compat/tsconfig.json
- rapier2d/tsconfig.json
- rapier3d/tsconfig.json
- src.ts/dynamics/rigid_body.ts
- src.ts/dynamics/rigid_body_set.ts
- src.ts/geometry/collider_set.ts
Changes:
1. ES6 output by default
2. an internal cache for created `RigidBody` and `Collider` instances
(actually wanted to make the 'raw' filed to be private as well to avoid user from calling `raw.remove` etc operations, and for internal friend classes to access this field, we can add `@ts-ignore` to force access this private field, but i saw other pipelines are all have this problem so in this PR i didn't change it)
3. a naive plain `userData` field in `RigidBody` class (just a stub)
4. 2 new methods: `getAllHandles` & `getAllColliders / getAllBodies`
Drawback:
when serialization / deserialization, `userData` will be lost, but i think this is normal because that field is just a handy handle, so user needs to take care of it.
Test:
> use cache mechanism to avoid creating unnecessary RigidBody / Collider instances.

- src.ts/dynamics/rigid_body.ts
`resetTorques` now invokes the correct function (`rbResetTorques`).
Apologies for the added line break at EOF, this was the doing of GitHub's web-based commit editor... :S
> Fix resetTorques

- .github/workflows/rapier-js-ci-build.yml
- .gitignore
- package-lock.json
- package.json
- rapier-compat/package-lock.json
Small ish PR to improve the CI setup.
Changes 
- Add `package-lock.json` to repo (improves CI install)
- Use matrix for OS builds
- Add dependencies to `package.json`
I'd like to investigate if we can cache the `cargo install` step since it takes around 5 min each run
> chore: use matrix to build

- src.ts/geometry/collider.ts
- src.ts/geometry/shape.ts
- src/geometry/collider.rs
- src/geometry/shape.rs
```
castShape
intersectsShape
contactShape
containsPoint
projectPoint
intersectsRay
castRay
castRayAndGetNormal
```
they are on `Collider` before, and now they are on `Shape` too, because these methods are duplicated, so i have 'merged' them into a trait and implemented it on `SharedShape`. please review the changes, thanks.
> added utilities for Shape

- package-lock.json
- package.json
- rapier2d/build_doc.sh
- rapier2d/tsconfig_typedoc.json
- rapier2d/typedoc.json
- rapier3d/build_doc.sh
- rapier3d/tsconfig_typedoc.json
- rapier3d/typedoc.json
Update `typedoc` to latest version and `typescript` to v4.6 (typedoc doesn't support 4.7 yet)
Had put a lot of exceptions in `intentionallyNotExported`, not sure if there is a better way? Should `QueryPipeline` be exported?
**Important**
The Rapier doc site needs to update the iframe src to point just to the `index.html` file, since `globals.html` has been removed from typedoc
> chore: update typedoc to 0.22

- src.ts/coarena.ts
- src.ts/dynamics/impulse_joint_set.ts
- src.ts/dynamics/multibody_joint_set.ts
- src.ts/dynamics/rigid_body_set.ts
- src.ts/geometry/collider.ts
- src.ts/geometry/collider_set.ts
- src.ts/pipeline/world.ts
- src/utils.rs
- testbed2d/src/Graphics.js
- testbed2d/src/demos/collisionGroups.js
- testbed2d/src/demos/convexPolygons.js
- testbed2d/src/demos/cubes.js
- testbed2d/src/demos/heightfield.js
- testbed2d/src/demos/keva.js
- testbed2d/src/demos/lockedRotations.js
- testbed2d/src/demos/polyline.js
- testbed2d/src/demos/revoluteJoints.js
- testbed3d/src/Graphics.js
- testbed3d/src/demos/ccd.js
- testbed3d/src/demos/collisionGroups.js
- testbed3d/src/demos/convexPolyhedron.js
- testbed3d/src/demos/damping.js
- testbed3d/src/demos/fountain.js
- testbed3d/src/demos/heightfield.js
- testbed3d/src/demos/joints.js
- testbed3d/src/demos/keva.js
- testbed3d/src/demos/lockedRotations.js
- testbed3d/src/demos/platform.js
- testbed3d/src/demos/pyramid.js
- testbed3d/src/demos/trimesh.js
This PR replaces our uses of `Map` by an arena that keeps objects stored based on their handles. The iteration order is always determined by the hander’s indices determined by the Rust arenas. That way, we maintain determinism of iteration order after deserialization.
> Ensure that the iteration orders remain the same after deserialization

- .github/workflows/rapier-js-ci-build.yml
- package-lock.json
- package.json
- rapier-compat/package.json
- rapier2d/build_rust.sh
- rapier3d/build_rust.sh
- testbed2d/package.json
- testbed3d/package.json
Cuts away ~5 min from each CI run (`cargo install wasm-pack`). Functionality seems to be the same from my testing. 
This comes with the added benefit of an easier setup for new contributors, since they no longer need to manually install `wasm-pack`.
> chore: install wasm-pack via npm

- .github/workflows/rapier-js-ci-build.yml
Cache cargo binaries (?) to improve CI speed. You can compare the CI times on the commits to see the difference, when using the cache it's ~4 min faster
> chore(ci): cache cargo

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
- testbed2d/src/Testbed.js
- testbed3d/src/Testbed.js
- Most APIs that relied on rigid-body handles or collider handles have been modified to rely on `RigidBody`
or `Collider` objects instead. Handles are now only needed for events and hooks.
- Rename STATIC to FIXED in the `ActiveCollisionTypes` flags.
- Add a lines-based debug-renderer. See [#119](https://github.com/dimforge/rapier.js/pull/119) for examples of
integration of the debug-renderer with `THREE.js` and `PIXI.js`.
- Each rigid-body, collider, impulse joint, and multibody joint now have a unique object instance. This instance
in only valid as long as the corresponding objects is inserted to the `World`.
- Add a `wakeUp: bool` argument to the `World.createImpulseJoint` and `MultibodyJointSet::createMultibodyJoint` to
automatically wake-up the rigid-bodies attached to the inserted …
> Release v0.8.0

- testbed2d/package-lock.json
- testbed2d/package.json
- testbed2d/src/Gui.ts
- testbed3d/package-lock.json
- testbed3d/package.json
- testbed3d/src/Gui.ts
`lil-gui` is a modern and maintained alternative to `dat.gui`. E.g. ThreeJS have migrated all their examples to use it
https://github.com/georgealways/lil-gui
The `onChange` cb has been removed from fns, otherwise pretty much a straight replacement.
> chore(testbed): replace dat.gui with lil-gui

- CHANGELOG.md
- Cargo.lock
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
Starting with this release, all the examples in `testbed2d` and `testbed3d` have been updated to `webpack 5`, and are written in Typescript. In addition, canary `0.0.0` releases will be generated automatically after each merge to the `master` branch.
-   Fix bug causing `World.intersectionPair` to always return `false`.
> Release v0.8.1

- src/dynamics/impulse_joint.rs
Motor configuration set the motor’s properties but didn’t actually set the motor as enabled, so it didn’t have any visible effect.
Fix #150
> Automatically enable a joint motor when configuring it.

- Cargo.lock
- Cargo.toml
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
- src/geometry/narrow_phase.rs
- src/geometry/shape.rs
- src/pipeline/query_pipeline.rs
This updates the internal Rust dependency to Rapier 0.16.0. This lets us benefit from the internal-edge problem fix for 3D triangle meshes and 3D heightfields.
> Update to rapier 0.16

- src.ts/dynamics/ccd_solver.ts
- src.ts/dynamics/impulse_joint_set.ts
- src.ts/dynamics/integration_parameters.ts
- src.ts/dynamics/island_manager.ts
- src.ts/dynamics/multibody_joint_set.ts
- src.ts/dynamics/rigid_body_set.ts
- src.ts/geometry/broad_phase.ts
- src.ts/geometry/collider_set.ts
- src.ts/geometry/narrow_phase.ts
- src.ts/pipeline/debug_render_pipeline.ts
- src.ts/pipeline/event_queue.ts
- src.ts/pipeline/physics_pipeline.ts
- src.ts/pipeline/query_pipeline.ts
- src.ts/pipeline/serialization_pipeline.ts
I sporadically get a `TypeError: this.raw is undefined` error from EventQueue, this could be a bug in my code where I call `.free()` to often. However I think the expected behavior is not to crash when doing so
> fix: don't panic if calling .free() multiple times

- src.ts/control/character_controller.ts
- Fix typos in character-controller docs.
- Make sure that `KinematicCharacterController.computedCollision` actually returns an object and populates the `collider` field.
> Fix typos in character-controller.

- .github/workflows/main.yml
- package-lock.json
- package.json
- rapier-compat/gen_src.sh
- rapier-compat/package.json
- rapier2d/build_all.sh
- rapier2d/build_doc.sh
- rapier2d/package-lock.json
- rapier2d/package.json
- rapier3d/build_all.sh
- rapier3d/build_doc.sh
- rapier3d/package-lock.json
- rapier3d/package.json
- testbed2d/package-lock.json
- testbed2d/package.json
- testbed3d/package-lock.json
- testbed3d/package.json
**changes**
- Make `rapier-compat` builds side-effect free. They no longer modify files outside the compat directory. It has caught be off guard several times that building `rapier3d-compat` "breaks" the `rapier3d` pkg
- Easier dev setup for rapier packages by adding a root package.json with scripts and that testbeds can reference (this will be needed for a workspace setup anyway)
- Use local rapier2d and rapier3d version in testbeds
> chore: make compat build side-effect free

- testbed2d/src/Gui.ts
- testbed3d/src/Gui.ts
Cleans up the current hacky approach to select the custom ms/step panel by default--instead inspects the number of children of the parent DOM element of all panels
> Fix statsjs default to custom panel on Firefox

- CHANGELOG.md
- Cargo.lock
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
- src.ts/dynamics/rigid_body.ts
- src.ts/dynamics/rigid_body_set.ts
- src.ts/geometry/collider.ts
- src.ts/geometry/collider_set.ts
- src.ts/pipeline/query_pipeline.ts
- src.ts/pipeline/world.ts
- src/dynamics/rigid_body.rs
- src/dynamics/rigid_body_set.rs
- src/geometry/collider.rs
- src/geometry/collider_set.rs
- src/pipeline/physics_pipeline.rs
- src/pipeline/query_pipeline.rs
-   Switch to Rapier 0.17.
-   Add `World.propagateModifiedBodyPositionsToColliders` to propagate rigid-bodies position changes to their attached
colliders.
-   Add `World.updateSceneQueries` to update the scene queries data structures without stepping the whole simulation.
-   Add `RigidBody.isEnabled, RigidBody.setEnabled, RigidBodyDesc.setEnabled` to disable a rigid-body (and all its
attached colliders) without removing it from the physics world.
-   Add `Collider.isEnabled, Collider.setEnabled, ColliderDesc.setEnabled` to disable a collider without removing it
from the physics world.
> Add collider/rigidbody enable/disable + add query pipeline update

- CHANGELOG.md
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
-   Add `World.propagateModifiedBodyPositionsToColliders` to propagate rigid-bodies position changes to their attached
colliders.
-   Add `World.updateSceneQueries` to update the scene queries data structures without stepping the whole simulation.
-   Add `RigidBody.isEnabled, RigidBody.setEnabled, RigidBodyDesc.setEnabled` to disable a rigid-body (and all its
attached colliders) without removing it from the physics world.
-   Add `Collider.isEnabled, Collider.setEnabled, ColliderDesc.setEnabled` to disable a collider without removing it
from the physics world.
-   Add shape-specific methods to modify a collider’s size: `Collider.setRadius, setHalfExtents, setRoundRadius, setHalfHeight`.
- Add a boolean argument to `RigidBody.setBodyType` to indicate if the rigid-body should awaken after …
> Release v0.11.0

- Cargo.lock
- src.ts/dynamics/rigid_body.ts
- src.ts/math.ts
- src/dynamics/rigid_body.rs
- src/math.rs
- Expose rigid property mass properties necessary for creating custom controllers in user-land, e.g. vehicle controllers
- In particular, I have been porting the bullet/cannon RaycastVehicleController to rapier.js, which uses rigid body inertia properties to calculate impulses for braking
- Addresses https://github.com/dimforge/rapier.js/issues/194
- Expose rigid body mass properties
- `invMass`
- `effectiveInvMass`
- `localCom`
- `worldCom`
- `invPrincipalInertiaSqrt`
- `principalInertia`
- `principalInertiaLocalFrame` (DIM3 only)
- `effectiveWorldInvInertiaSqrt`
- `effectiveAngularInertia`
> Expose rigid body mass properties

- src/math.rs
- Minor docs fix for `RawSpdMatrix3::elements`, making it consistent with the js `SpdMatrix3::elements`
> fix: docs for RawSpdMatrix3::elements

- CHANGELOG.md
- Cargo.lock
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
This should address #207. In some cases, a dynamic body that would be enabled and then re-enabled could start acting as kinematic bodies because their mass properties were not recomputed properly.
> Uses Rapier 0.17.1

- CHANGELOG.md
- src.ts/control/index.ts
- src.ts/control/ray_cast_vehicle_controller.ts
- src.ts/pipeline/world.ts
- src/control/mod.rs
- src/control/ray_cast_vehicle_controller.rs
This makes it possible to use the dynamic vehicle controller based on ray-casts for the wheels that was introduced in Rapier 0.17.
> Add bindings for the vehicle controller

- Cargo.lock
- Cargo.toml
- src.ts/geometry/collider.ts
- src.ts/pipeline/event_queue.ts
- src.ts/pipeline/physics_hooks.ts
- src/control/character_controller.rs
Currently when trying to build `rapier3d` from sources by using `npm run build` command in `./rapier3d` directory, there are two typescript errors:
```
pkg/src/geometry/collider.ts:1038:9 - error TS2322: Type '0' is not assignable to type 'ActiveEvents'.
1038         this.activeEvents = 0;
~~~~~~~~~~~~~~~~~
pkg/src/geometry/collider.ts:1039:9 - error TS2322: Type '0' is not assignable to type 'ActiveHooks'.
1039         this.activeHooks = 0;
~~~~~~~~~~~~~~~~
Found 2 errors in the same file, starting at: pkg/src/geometry/collider.ts:1038
```
Though it will work after transpiling, typescript type check requires enum value to be passed if variable has type `ActiveEvents` or `ActiveHooks`. Possible solutions is to declare these variables as `ActiveEvents | 0`, or simply add special value …
> Fixed typescript build of rapier3d

- src.ts/dynamics/impulse_joint.ts
- src/dynamics/joint.rs
This allows generic joints with custom axes masks to be created. The joint axes are represented with a typescript bitflag enum.
Currently it's only exposed for 3D impulse joints, since that's what I use and have tested, but I can expand it to the other types if needed. Just might take a bit to find the free time.
Let me know if anything looks weird!
> Expose 3D generic impulse joints

- src.ts/geometry/collider.ts
- src.ts/geometry/shape.ts
- src.ts/pipeline/query_pipeline.ts
- src.ts/pipeline/world.ts
I'm not 100% sure ; the sentence "on a path to exist that penetration state" feels a bit weird, I'm not sure if I could read it either:
- "enter" that penetration state
- or it's a typo ? "exit" that penetration state
> Fix typo in "'castShape' functions

- CHANGELOG.md
- Cargo.lock
- rapier2d/Cargo.toml
- rapier3d/Cargo.toml
-   Update from the rust library of rapier 0.19 to 0.22,
see [rapier's changelog](https://github.com/dimforge/rapier/blob/master/CHANGELOG.md#v0210-23-june-2024) for more
context.
-   Added `RigidBody.userForce` function to retrieve the constant force(s) the user added to a rigid-body
-   Added `RigidBody.userTorque` function to retrieve the constant torque(s) the user added to a rigid-body
> Release v0.14.0

- CHANGELOG.md
- rapier-compat/README.md
- rapier2d/package-lock.json
- rapier2d/package.json
- rapier3d/package-lock.json
- rapier3d/package.json
- testbed2d/package-lock.json
- testbed2d/package.json
- testbed2d/src/Gui.ts
- testbed2d/src/Testbed.ts
- testbed2d/static/index.html
- testbed3d/package-lock.json
- testbed3d/package.json
- testbed3d/src/Gui.ts
- testbed3d/src/Testbed.ts
- testbed3d/static/index.html
#294 
Hello, i have choosen xxHash128 which is a non cryptographical hashing function and stay with the lenght of 128 bits to match the previous output with md5.
You can view the difference in term of performance bellow
Before :
[https://rapier.rs/demos3d/index.html](https://rapier.rs/demos3d/index.html)
[https://rapier.rs/demos2d/index.html](https://rapier.rs/demos2d/index.html)
After :
[https://pi-univers.fr/rapier.js/testbed3d/dist/](https://pi-univers.fr/rapier.js/testbed3d/dist/)
[https://pi-univers.fr/rapier.js/testbed2d/dist/](https://pi-univers.fr/rapier.js/testbed2d/dist/)
> Remove md5 and use xxHash128 for hashing algorithm in debug infos

- .github/workflows/main.yml
- builds/prepare_builds/templates/build_rust.sh.tera
- rapier-compat/build-rust.sh
- Fix https://github.com/dimforge/rapier.js/issues/314
> Fix rapier(x)d-simd-compat to use simd instructions

- CHANGELOG.md
- src.ts/dynamics/rigid_body.ts
- src/dynamics/rigid_body.rs
> Add rigidBody.velocityAtPoint

- CHANGELOG.md
- Cargo.lock
- builds/prepare_builds/templates/Cargo.toml.tera
- src.ts/geometry/collider.ts
- src.ts/geometry/shape.ts
- src/geometry/collider.rs
- src/geometry/shape.rs
- testbed2d/package-lock.json
- testbed2d/src/Graphics.ts
- testbed2d/src/demos/voxels.ts
- testbed2d/src/index.ts
- testbed3d/package-lock.json
- testbed3d/src/Graphics.ts
- testbed3d/src/demos/voxels.ts
- testbed3d/src/index.ts
This PRs adds partial support of a new dedicated shape for colliders made of voxels. This shape type is designed to handle efficiently, and without "internal edges" artifacts, collision detection with objects defined as a set of voxels. Each `Voxels` shape is free to have their own voxel size; and can be rotated/translated arbitrarily as a whole. The voxel size can be different along each axis (i.e. it can be a rectangle instead of just a cube).
This feature is still experimental as it is missing some elements. The following is supported:
- Ray-casting.
- Point-projection (very unoptimized).
- Contact-manifold generation with convex shapes.
- Conversion from and to meshes/polylines.
- Conversion to outlines for debug-rendering.
- Dynamic addition or removal of individual voxels.
Notable …
> Add support for voxels colliders

- CHANGELOG.md
- Cargo.lock
- builds/prepare_builds/templates/Cargo.toml.tera
- src.ts/geometry/collider.ts
- src/geometry/collider.rs
- testbed2d/src/Graphics.ts
- testbed3d/src/Graphics.ts
- Added `Collider.clearShapeCache` to release the reference to the JS shape stored in the collider, oor too force its
recomputation the next time the collider shape is accessed.
- Added support for shape-casting involving Voxels colliders.
- Added support for CCD involving Voxels colliders.
> feat: add support for shape-casting and ccd on voxels collider

- CHANGELOG.md
- Cargo.lock
- builds/prepare_builds/templates/Cargo.toml.tera
Calling `coollider.setVoxel` on a collider with a `Voxels` shape currently leads to an instantaneous hang of the application. This has been fixed in parry 0.20.2. This PR updates that dependency and releases rapier.js 0.16.2.
> Fix infinite loop in collider.setVoxel

- CHANGELOG.md
- Cargo.lock
- builds/prepare_builds/templates/Cargo.toml.tera
- src.ts/geometry/collider.ts
- src.ts/geometry/shape.ts
- src/geometry/collider.rs
- src/geometry/shape.rs
- Fix sensor events not triggering when hitting a voxels collider.
- Added support for voxels colliders attached to dynamic rigid-bodies.
- Added force calculation between colliding voxels/voxels and voxels/compound shapes.
> Release v0.17.0

- CHANGELOG.md
- Cargo.lock
- builds/prepare_builds/templates/Cargo.toml.tera
- src.ts/geometry/collider.ts
- src.ts/pipeline/debug_render_pipeline.ts
- src.ts/pipeline/world.ts
- src/geometry/collider.rs
- src/geometry/collider_set.rs
- src/geometry/shape.rs
- src/pipeline/debug_render_pipeline.rs
- Added optional arguments to `World.debugRender(filterFlags, filterPredicate)` to prevent some colliders from being
rendered.
- Added `Collider.combineVoxelStates` to ensure two adjacent voxels colliders don’t suffer from the internal edges
problem, and `Collider.propagateVoxelChange` to maintain that coupling after modifications with `.setVoxel`.
> Release v0.17.1

- CHANGELOG.md
- builds/prepare_builds/templates/Cargo.toml.tera
- src.ts/exports.ts
- src/lib.rs
- Added the function `RAPIER.reserveMemory` to instruct the internal allocator to pre-allocate more memory in preparation
for future operations. This typically called only once after initializing the WASM module.
> feat: add reserveMemory

- rapier-compat/rollup.config.js
- Follow up to https://github.com/dimforge/rapier.js/pull/334#issuecomment-3155512697
- Fix #332
I tested this with https://github.com/Vrixyz/rapierjs-no-bundler/tree/main/with_npm and https://github.com/mattvb91/rapierjs-module-bug/tree/master.
> Add exports config to help commonjs with nodenext

- CHANGELOG.md
- builds/prepare_builds/templates/Cargo.toml.tera
- Update to Rapier 0.28.0 which includes performance improvements when CCD is active and when
the user applies modification to a collider or rigid-body.
- Another attempt to fix bundlerless module import with rapier-compat.
> Release v0.18.1
