dimforge/rapier.js

rapier2d/build_typescript.sh, rapier3d/build_typescript.sh
=> Modify our build script in order to keep the typescript files inside of the NPM package.

rapier2d/Cargo.toml, rapier3d/Cargo.toml, testbed2d/package.json, testbed3d/package.json, testbed3d/webpack.config.js
=> Fix crash on iOS safari

src/dynamics/rigid_body.rs
=> fix #57: lockRotation will lock its translations

src.ts/dynamics/rigid_body.ts, src/dynamics/rigid_body.rs
=> add userData for RigidBody

src.ts/dynamics/impulse_joint_set.ts, src.ts/dynamics/multibody_joint_set.ts
=> fix for #85: take jointType into account when retrieve them with forEach

Cargo.toml, src.ts/dynamics/impulse_joint.ts, src.ts/dynamics/rigid_body_set.ts, src.ts/geometry/collider.ts, src.ts/geometry/shape.ts, src.ts/geometry/toi.ts, src.ts/pipeline/query_pipeline.ts, src.ts/pipeline/world.ts, src/dynamics/impulse_joint_set.rs, src/dynamics/joint.rs, src/dynamics/multibody_joint_set.rs, src/dynamics/rigid_body_set.rs, src/geometry/collider.rs, src/geometry/shape.rs, src/geometry/toi.rs, src/pipeline/query_pipeline.rs, testbed3d/src/demos/platform.js
#82
for `sweepBetween` / `intersectsBetween`... i guess we need a better name for this?
or maybe this should go to `shape.xxx` ?
=> added collider.castShape & collider.castCollider

src.ts/geometry/collider.ts, src.ts/geometry/contact.ts, src.ts/geometry/shape.ts, src/geometry/collider.rs, src/geometry/contact.rs, src/geometry/mod.rs, src/geometry/shape.rs
shape contacts shape
collider contacts shape / collider
=> contact support

src.ts/dynamics/rigid_body.ts, src/dynamics/rigid_body.rs
added missing `setBodyType` on `RigidBody` class.
fix for #102
test:
https://user-images.githubusercontent.com/850854/162432650-1cc3b8f5-6a74-4ddd-a27e-064aa59e98bf.mp4
=> added missing `setBodyType` on `RigidBody` class

src.ts/geometry/collider.ts, src.ts/geometry/shape.ts
params / ts definition improvement.
fix #59
=> fix #59 improve TS definition / params

src.ts/dynamics/rigid_body.ts, src.ts/dynamics/rigid_body_set.ts, src/dynamics/rigid_body_set.rs
added missing `sleeping` for `RigidBodyDesc`
#107
=> added `sleeping` for `RigidBodyDesc`

testbed2d/package-lock.json, testbed2d/package.json, testbed2d/src/Graphics.js, testbed2d/webpack.config.js, testbed3d/package-lock.json, testbed3d/package.json, testbed3d/webpack.config.js
Upgrade webpack to the latest version. Everything seems to run fine in my testing
=> chore(testbed): upgrade to webpack 5

src/geometry/narrow_phase.rs
=> Fix handles usage in NarrowPhase::intersection_pair

rapier-compat/package.json, src.ts/pipeline/query_pipeline.ts, src.ts/pipeline/world.ts, src/pipeline/query_pipeline.rs
the missing one not in #110 before, so add it now.
btw, modified the ';' to '&&' because '&&' compatiable for both Mac & Win
=> added the missing one before didn't add.

Cargo.lock, rapier2d/Cargo.toml, rapier3d/Cargo.toml
=> Switch to the latest version of wasm-bindgen

package-lock.json, package.json, testbed2d/package-lock.json, testbed2d/package.json, testbed3d/package-lock.json, testbed3d/package.json
Update deps to the latest version (except pixi.js which requires some more changes)
=> chore: update dependencies

src.ts/geometry/collider.ts, src/geometry/collider.rs
Hi @sebcrozet - As discussed a few weeks ago on the Discord channel, here are changes that will allow users to adjust a collider's shape size.
=> Add the ability to update the size properties of a collider

CHANGELOG.md, src.ts/control/character_controller.ts, src/control/character_controller.rs
Changed all instances of transformation to transformationDelta, as well as renamed two public functions
=> Transform naming changes

Cargo.lock, Cargo.toml, src.ts/control/ray_cast_vehicle_controller.ts, src/control/ray_cast_vehicle_controller.rs
This gives access to more information about wheel suspensions and their ray-casting result.
This also give access to wheel friction.
=> Give access to more vehicle controller fields

.github/workflows/main.yml
Based on #306 
Upgrades all GitHub actions to v4 and Node to current LTS (22)
=> Upgrade GitHub actions and Node

CHANGELOG.md, Cargo.toml, rapier2d/Cargo.toml, rapier3d/Cargo.toml, src.ts/control/index.ts, src.ts/control/pid_controller.ts, src.ts/pipeline/world.ts, src/control/mod.rs, src/control/pid_controller.rs, src/dynamics/impulse_joint_set.rs, src/geometry/shape.rs, src/pipeline/physics_hooks.rs, testbed2d/src/demos/pidController.ts, testbed2d/src/index.ts, testbed3d/src/demos/pidController.ts, testbed3d/src/index.ts
Currently, Rapier implements a character controller based on kinematic rigid bodies and shape queries. A second common paradigm for character controllers are velocity-based control of dynamic rigid-bodies. This as many advantages over kinematic character controller like the natural interaction with other dynamic bodies and fact it doesn’t need any scene queries (ray-cast/shape-cast) to operate. However, it provides slightly less control for non-physical behaviors than what we can get from kinematic character controllers.
This PR introduces a `PidController` implementing the well-known concept of [Proportional-Integral-Derivative control](https://en.wikipedia.org/wiki/Proportional%E2%80%93integral%E2%80%93derivative_controller). This tool can be used to facilitate the implementation of …
=> feat: add PID controller implementations
